application: happiemeter
version: 1
runtime: python27
api_version: 1
threadsafe: true   # set to false if/when running tests

handlers:
- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon\.ico

- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /javascript
  static_dir: static/javascript

- url: /fonts
  static_dir: static/fonts

- url: /test.*
  login: admin
  script: gaeunit.application

# discover services at: http://localhost:8080/_ah/api/explorer
- url: /_ah/spi/.*
  script: services.application
#  script: tictactoe_api.application

#- url: /services/user.*
#  script: services.application

#- url: /hello.*
#  script: hello_service.application

- url: /.*
  script: happymeter.application

libraries:
- name: webapp2
  version: latest

- name: django
  version: latest

- name: endpoints
  version: 1.0

- name: jinja2
  version: latest